server:
  port: 8999
spring:
  profiles:
    active: loc
  application:
    name: firefly
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    com.cafi.firefly.service.feignClient: debug
tencent:
  SecretId: AKIDYu13yfWoxDDxo7xJcdRcWGn56q3pdaZH
  SecretKey: mLempvmMgmpfPRFqCIgoiOt9BvshWEh7


